### ISSUE TITLE
NoClassDefFoundError while downloading on Gradle-3.0-milestone-1

### ISSUE THREAD

**Issue by zolotov** [michel-kraemer/gradle-download-task#47]
Since ProgressLogger was moved the following exception is thrown while downloading

```
Caused by: java.lang.NoClassDefFoundError: Lorg/gradle/logging/ProgressLogger;
	at org.gradle.internal.metaobject.BeanDynamicObject.getMetaClass(BeanDynamicObject.java:139)
	at org.gradle.internal.metaobject.BeanDynamicObject.access$400(BeanDynamicObject.java:55)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:379)
	at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:170)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:59)
	at build_bde9ot97vy9vu4gqda0wc6vps$_downloadAndUnzip_closure9.doCall(/Users/zolotov/dev/intellij-plugins/intellij-go/build.gradle:128)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
	at de.undercouch.gradle.tasks.download.DownloadExtension.configure(DownloadExtension.java:42)
	at de.undercouch.gradle.tasks.download.DownloadExtension.configure(DownloadExtension.java:29)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:104)
	at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
	at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
	at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
	at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:215)
	at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
	at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	at build_bde9ot97vy9vu4gqda0wc6vps.downloadAndUnzip(/Users/zolotov/dev/intellij-plugins/intellij-go/build.gradle:127)
	at build_bde9ot97vy9vu4gqda0wc6vps$_run_closure7.doCall(/Users/zolotov/dev/intellij-plugins/intellij-go/build.gradle:103)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:587)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:80)
	at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:76)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 71 more
```

**Comment by michel-kraemer** [comment]
Thanks for reporting. This issue pops up from time to time. I'll look into it and get back to you.

**Comment by michel-kraemer** [comment]
I uploaded a new snapshot that should fix the issue for Gradle 2.14. I guess it will work with Gradle 3.0-milestone-1 too.

May I ask you to test it, so I can release a new version of the plugin?

Please use the following to apply the snapshot:

```gradle
buildscript {
    repositories {
        jcenter()
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
    }
    dependencies {
        classpath 'de.undercouch:gradle-download-task:3.1.0-SNAPSHOT'
    }
}

apply plugin: 'de.undercouch.download'
```

Remove the plugin from your `plugin` section in the build file.

Thanks for your support!

**Comment by crosstowncoder** [comment]
Fix works fine with gradle 2.14
Thanks!

**Comment by mangan77** [comment]
Same here. Snapshot works.

**Comment by michel-kraemer** [comment]
Thanks for the feedback. Has anybody tested it with Gradle 3.0 yet?

**Comment by zolotov** [comment]
@michel-kraemer sorry for a delay, 3.1.0-SNAPSHOT works fine with Gradle 3.0-milestone2. Thank you

**Comment by michel-kraemer** [comment]
Thanks for the feedback. I'll close this issue and release a new version in the next couple of days.

**Comment by cdancy** [comment]
Hitting this issue with gradle 2.14.1 using version 3.1.1 of this plugin

	error	24-Jul-2016 12:02:22	Caused by: java.lang.NoClassDefFoundError: Lorg/gradle/logging/ProgressLogger;
	error	24-Jul-2016 12:02:22		at org.gradle.internal.metaobject.BeanDynamicObject.getMetaClass(BeanDynamicObject.java:138)
	error	24-Jul-2016 12:02:22		at org.gradle.internal.metaobject.BeanDynamicObject.access$300(BeanDynamicObject.java:55)
	error	24-Jul-2016 12:02:22		at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:186)
	error	24-Jul-2016 12:02:22		at org.gradle.internal.metaobject.BeanDynamicObject.getProperty(BeanDynamicObject.java:149)
	error	24-Jul-2016 12:02:22		at org.gradle.internal.metaobject.ConfigureDelegate.getProperty(ConfigureDelegate.java:116)
	error	24-Jul-2016 12:02:22		at integration_15c2phd4z59bmwxlepxovsesm$_run_closure14$_closure30$_closure31.doCall(/bamboo-agent-home/xml-data/build-dir/PRPCHEADCV-GCCV-VPI/dist/test/integration.gradle:221)
	error	24-Jul-2016 12:02:22		at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	error	24-Jul-2016 12:02:22		at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:107)
	error	24-Jul-2016 12:02:22		at de.undercouch.gradle.tasks.download.DownloadExtension.configure(DownloadExtension.java:42)
	error	24-Jul-2016 12:02:22		at de.undercouch.gradle.tasks.download.DownloadExtension.configure(DownloadExtension.java:29)
	error	24-Jul-2016 12:02:22		at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:59)
	build	24-Jul-2016 12:02:22	
	error	24-Jul-2016 12:02:22		at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
	error	24-Jul-2016 12:02:22		at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
	error	24-Jul-2016 12:02:22		at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:215)
	error	24-Jul-2016 12:02:22		at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
	error	24-Jul-2016 12:02:22		at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
	error	24-Jul-2016 12:02:22		at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
	error	24-Jul-2016 12:02:22		at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	error	24-Jul-2016 12:02:22		at org.gradle.internal.metaobject.BeanDynamicObject$GroovyObjectAdapter.invokeOpaqueMethod(BeanDynamicObject.java:440)
	error	24-Jul-2016 12:02:22		at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:397)
	error	24-Jul-2016 12:02:22		at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:169)
	error	24-Jul-2016 12:02:22		at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:80)
	error	24-Jul-2016 12:02:22		at integration_15c2phd4z59bmwxlepxovsesm$_run_closure14$_closure30.doCall(/bamboo-agent-home/xml-data/build-dir/PRPCHEADCV-GCCV-VPI/dist/test/integration.gradle:220)
	error	24-Jul-2016 12:02:22		at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
	error	24-Jul-2016 12:02:22		at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
	error	24-Jul-2016 12:02:22		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	error	24-Jul-2016 12:02:22		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	error	24-Jul-2016 12:02:22		... 68 more
	error	24-Jul-2016 12:02:22	Caused by: java.lang.ClassNotFoundException: org.gradle.logging.ProgressLogger
	error	24-Jul-2016 12:02:22		... 95 more
	error	24-Jul-2016 12:02:22	
	build	24-Jul-2016 12:02:22	BUILD FAILED
	build	24-Jul-2016 12:02:22	
	build	24-Jul-2016 12:02:22	Total time: 28 mins 22.432 secs
