### ISSUE TITLE
Plugin doesn't work with the latest nightly (1.12-20140127015041+0000)

### ISSUE THREAD

**Issue by eddgrant** [michel-kraemer/gradle-download-task#3]
Hi,

Lovely plugin, thanks for putting it together. Just raising this as I noticed the plugin doesn't work with the 1.12-20140127015041+0000 nightly Gradle build. The error I get is:

```
Caused by: java.lang.NoSuchMethodError: org.gradle.api.internal.project.ProjectInternal.getServices()Lorg/gradle/internal/service/scopes/ServiceRegistryFactory;
    at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:110)
    at de.undercouch.gradle.tasks.download.Download.download(Download.java:46)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:219)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:212)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:201)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:533)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:516)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
```

From what I can tell this is due to the plugin's use of `org.gradle.api.internal.project.ProjectInternal`, which I think is an internal Gradle API and therefore subject to change without notice. I'm guessing the `getServices()` method has been removed at some point in this case?

Anyhoo, thought I'd mention this in case it's of some benefit.

Cheers,

Edd
